version: '3'

networks:
    default:
        external: true
        name: "mariadb_database"

services:
  web:
    container_name: gitea
    image: gitea/gitea:1-rootless
    volumes:
      - /home/roman/.self-hosted/gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:22"

    environment:
        - USER_UID=1000
        - USER_GID=1000
        - GITEA__database__DB_TYPE=mysql
        - GITEA__database__HOST=mariadb:3306
        - GITEA__database__NAME=gitea
        - GITEA__database__USER=gitea
        - GITEA__database__PASSWD=gitea
    # depends_on:
    #   - db
    # links:
    #   - "db"
    # networks:
    #   - "mariadb_database"
    restart: always
#   db:
#     image: mariadb
#     restart: always
#     environment:
#       - MYSQL_ROOT_PASSWORD=changeme
#       - MYSQL_DATABASE=gitea
#       - MYSQL_USER=gitea
#       - MYSQL_PASSWORD=changeme
#     volumes:
#       - ./db/:/var/lib/mysql
