# Use root/example as user/password credentials
version: '3'

services:

  db:
    container_name: mariadb
    hostname: mariadb
    image: mariadb
    restart: always
    environment:
        - MYSQL_ROOT_PASSWORD=root_password
        - USER_UID=1000
        - USER_GID=1000
    volumes:
      - /home/roman/.self-hosted/mariadb/db/:/var/lib/mysql
    #   - /etc/timezone:/etc/timezone:ro
    #   - /etc/localtime:/etc/localtime:ro
    networks:
      - "database"
    #   - "gitea"

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
        - "database"

networks:
    database:
    # gitea:
